name: Deploy to Infomaniak via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Create underscore directory and copy redirect
        run: |
          mkdir -p ./dist/_
          cp ./public/_redirect.html ./dist/_/index.html

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./sites/portfolio.bryan-thierry.fr/ # ⬅️ CHANGEMENT ICI
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
